package modelo;

/**
 * Classe que contém os vetores de String relacionados a cada subtema.
 * @author Israel
 * @version 1.0 (Abr 2021)
 */
public class ListaDePalavras extends ModeloDeListaDePalavras {
	
	/**
	 * Construtor para aciona construtor da superclasse ModeloDeListaDePalavras passando cada um dos vetores como parâmetro.
	 * @param strings
	 */
	public ListaDePalavras(String[] strings) {
		super(strings);
	}

	private String nomeFeminino[] = {"KONAN", "VIDEL", "AGATHA", "CAMILA", "ESTHER", "ISIS", "MAITÊ", "NATÁLIA", "ALÍCIA",
			"CAROLINA",	"FERNANDA",	"JOANA", "MALU", "NICOLE", "AMANDA", "CATARINA", "GABRIELA", "LAÍS", "MARIA", "OLÍVIA",
			"ANA", "CECÍLIA", "TEMARI", "LARA", "ANKO", "PIETRA", "ANTONELA", "CLARA", "GEOVANNA", "LARISSA", "MARIANA",
			"RAFAELA", "AURORA", "CLARICE",	"GIULIA", "LAVÍNIA", "MARINA", "REBECA", "BÁRBARA",	"EDUARDA", "HELOÍSA", "LETÍCIA",
			"MAYA",	"SARA", "BEATRIZ", "ELISA", "ISABEL", "LIZ", "MELISSA", "SOPHIE", "BIANCA",	"EMANUELLY", "ISABELLY", "LORENA",
			"MILENE", "STELLA",	"BRUNA", "EMILLY", "ISADORA", "LUANA", "MIRELLA", "VITÓRIA", "YASMIN", "AMELIA", "NATASHA",
			"KAREN", "ALICE", "RAABE", "YUKIMI", "SAORI"};
	private String nomeMasculino[] = {"MINATO", "GOHAN", "CHARLES", "BENJAMIN", "ARTHUR", "AUGUSTO", "BERNARDO", "BENTO",
			"BRUNO", "BRYAN", "CAIO", "CALEBE", "CARLOS", "CAUÃ", "DANIEL", "DAVI", "EDUARDO", "EMANUEL", "ENZO", "ERICK",
			"FELIPE", "FERNANDO", "FRANCISCO", "GABRIEL", "GUILHERME", "GUSTAVO", "HEITOR", "HENRIQUE", "HENRY", "ISAAC",
			"JOAQUIM", "JOSÉ", "JOÃO", "CAIQUE", "LEONARDO", "LEVI", "LORENZO", "LUAN", "LUCAS", "MARTIM", "MATHEUS",
			"MIGUEL", "MATIAS", "SHINO", "NATHAN", "OLIVER", "OTÁVIO", "PEDRO", "PIETRO", "RAFAEL", "RAUL", "RAVI",
			"RODRIGO", "RYAN", "ANTÔNIO", "SAMUEL", "TEODORO", "THIAGO", "VICENTE", "THOMAS", "VINÍCIUS", "VITOR", "YUKI",
			"MATTHEW", "ROBERT", "SMITH", "RORY", "CRAIG", "HAKU", "LOGAN"};
	private String paises[] = {"AFEGANISTÃO", "ÁFRICA DO SUL", "ALBÂNIA", "ALEMANHA", "ANDORRA", "ANGOLA",
			"ANTÍGUA E BARBUDA", "ARÁBIA SAUDITA", "ARGÉLIA", "ARGENTINA", "ARMÊNIA", "AUSTRÁLIA", "ÁUSTRIA",
			"BAHAMAS", "BAHREIN", "BANGLADESH", "BÉLGICA", "BELIZE", "BIELORRÚSSIA", "BOLÍVIA", "BÓSNIA E HERZEGOVINA",
			"BOTSUANA", "BRASIL", "BRUNEI", "BULGÁRIA", "BURKINA FASO", "CABO VERDE", "CAMARÕES", "CAMBOJA", "CANADÁ",
			"CATAR", "CAZAQUISTÃO", "CHADE", "CHILE", "CHINA", "CHIPRE", "COLÔMBIA", "COREIA DO NORTE", "COREIA DO SUL",
			"COSTA DO MARFIM", "COSTA RICA", "CROÁCIA", "CUBA", "DINAMARCA", "EGITO", "EL SALVADOR", "EMIRADOS ÁRABES UNIDOS",
			"EQUADOR", "ERITREIA", "ESCÓCIA", "ESLOVÁQUIA", "ESLOVÊNIA", "ESPANHA", "ESTADOS FEDERADOS DA MICRONÉSIA",
			"ESTADOS UNIDOS DA AMÉRICA", "ESTÔNIA", "ETIÓPIA", "FIJI", "FILIPINAS", "FINLÂNDIA", "FRANÇA", "GABÃO",
			"GÂMBIA", "GEÓRGIA", "GRANADA", "GRÉCIA", "GUATEMALA", "HAITI", "HOLANDA", "HONDURAS", "HUNGRIA",
			"IÊMEN", "ÍNDIA", "INDONÉSIA", "INGLATERRA", "IRÃ", "IRAQUE", "IRLANDA DO NORTE", "IRLANDA", "ISLÂNDIA",
			"ISRAEL", "ITÁLIA", "JAMAICA", "JAPÃO", "JORDÂNIA", "KUWAIT", "LAOS", "LESOTO", "LETÔNIA", "LÍBANO",
			"LIBÉRIA", "LÍBIA", "LITUÂNIA", "LUXEMBURGO", "MACEDÔNIA", "MADAGASCAR", "MALÁSIA", "MALAWI", "MALDIVAS",
			"MARROCOS", "MAURITÂNIA", "MÉXICO", "MIANMAR", "MICRONÉSIA", "MOÇAMBIQUE", "MÔNACO", "MONGÓLIA", 
			"MONTENEGRO", "NAMÍBIA", "NEPAL", "NICARÁGUA", "NÍGER", "NIGÉRIA", "NORUEGA", "NOVA ZELÂNDIA",
			"PAÍS DE GALES", "PAÍSES BAIXOS", "PALAU", "PALESTINA", "PANAMÁ", "PAPUA NOVA GUINÉ", "PAQUISTÃO",
			"PARAGUAI", "PERU", "POLÔNIA", "PORTUGAL", "QUÊNIA", "QUIRGUISTÃO", "REPÚBLICA DEMOCRÁTICA DO CONGO",
			"REPÚBLICA DOMINICANA", "REPÚBLICA TCHECA", "ROMÊNIA", "RÚSSIA", "SÃO TOMÉ E PRÍNCIPE", "SENEGAL",
			"SERRA LEOA", "SÉRVIA", "SEYCHELLES", "SÍRIA", "SOMÁLIA", "SRI LANKA", "SUDÃO", "SUÉCIA", "SUÍÇA",
			"SURINAME", "TAILÂNDIA", "TAIWAN", "TANZÂNIA", "TRINIDAD E TOBAGO", "TUNÍSIA", "TURCOMENISTÃO",
			"TURQUIA", "TUVALU", "UCRÂNIA", "UGANDA", "URUGUAI", "UZBEQUISTÃO", "VATICANO", "VENEZUELA",
			"VIETNÃ", "ZÂMBIA", "ZIMBÁBUE", "WAKANDA"};
	private String cidades[] = {"LUZIÂNIA", "INVERNESS", "LONDRES", "ACAPULCO", "MACHU PICCHU", "SYDNEY", "MELBOURNE",
			"JOHANESBURGO", "VICTÓRIA", "VIENA", "MELK", "SALZBURG", "JERUSALÉM", "BANGKOK", "KUALA LUMPUR", "PEQUIM",
			"ROMA", "PARIS", "BARCELONA", "BERLIM", "LISBOA", "AMSTERDÃ", "VENEZA", "ATENAS", "ISTAMBUL", "MOSCOU",
			"BUDAPESTE", "PRAGA", "SEVILLA", "GRANADA", "BRASÍLIA", "BONITO", "ILHÉUS", "CABO FRIO", "RIO DAS OSTRAS",
			"RIO DE JANEIRO", "BÚZIOS", "JERICOACOARA", "GLASGOW", "MADRID", "FLORENÇA", "VARSÓVIA", "MILÃO", "BRUXELAS",
			"PORTO", "ESTOCOLMO", "NICE", "NÁPOLES", "ZAGREBE", "ZURIQUE", "BELGRADO", "MARSELHA", "RAVENA", "SIENA",
			"MANCHESTER", "EDIMBURGO", "NOTTINGHAM", "SOUTHAMPTON", "SWANSEA", "NORWICH", "TORONTO", "MONTREAL",
			"HIROSHIMA", "NAGASAKI", "TÓQUIO", "YOKOHAMA", "SHIZOUKA", "YAMANASHI", "MINATO", "WUHAN", "XANGAI", 
			"ZHENGZHOU", "BUENOS AIRES", "MONTEVIDÉU", "USHUAIA", "CARACAS", "GUAIAQUIL", "GUARAPARI", "NOVA YORK",
			"LOS ANGELES", "OTTAWA", "GUADALAJARA", "TIJUANA", "PHOENIX", "MONTERREY", "HAVANA", "SEATTLE", "TEOTIHUACAN",
			"MONTE CARMELO", "SUZANO", "MORRINHOS", "PIRENÓPOLIS"};
	private String animais[] = {"GAMBÁ", "TARTARUGA", "ABELHA", "ANDORINHA", "BABUÍNO", "BALEIA", "CACHORRO",
			"CAMALEÃO", "DRAGÃO-DE-KOMODO", "DROMEDÁRIO", "EMA", "ELEFANTE", "FOCA", "FLAMINGO", "GOLFINHO", "GUAXINIM",
			"HIPOPÓTAMO", "HIENA", "IGUANA", "IMPALA", "JAGUAR", "JACARÉ", "KAKAPO", "KIWI", "LEÃO", "LAGARTO", "MACACO",
			"MUSARANHO", "NAJA", "NARVAL", "OVELHA", "ORANGOTANGO", "PAPAGAIO", "PERDIZ", "QUATI", "QUEIXADA", "RAPOSA",
			"RATO", "SARDINHA", "SAGUI", "TIGRE", "TAMANDUÁ-BANDEIRA", "URSO-POLAR", "URUBU", "VEADO", "VACA", "WALLABY",
			"XEXÉU", "XARÉU", "YAK", "ZEBRA", "ZEBU", "GUEPARDO", "ONÇA", "GORILA", "LEOPARDO", "PINGUIM", "COALA", 
			"CANGURU", "PREGUIÇA", "CACHALOTE", "CAMUNDONGO", "CÁGADO", "CANÁRIO", "CAPIVARA", "CARACOL", "CARANGUEJO",
			"CARNEIRO", "CARRAPATO", "CASCAVEL", "CASTOR", "CAVALO", "CEGONHA", "CENTOPEIA", "CHIMPANZÉ", "CHINCHILA",
			"CHITA", "CIGARRA", "CISNE", "COBRA", "CODORNA", "COELHO", "COIOTE", "CORUJA", "CORVO", "CROCODILO", 
			"DRAGÃO-VOADOR", "ESCARAVELHO", "FALCÃO", "GATO", "GAVIÃO", "GAZELA", "GARÇA", "INHAMBU", "JOÃO-DE-BARRO",
			"LINCE", "MARIMBONDO", "MORCEGO", "MORSA", "ORNITORRINCO", "PANDA", "PANTERA", "QUEM-TE-VESTIU",
			"QUERO-QUERO", "QUETZAL", "TUCANO", "VIÚVA-NEGRA", "XOFRANGO", "YNAMBU", "YORKSHIRE", "ZANGÃO"};
	private String plantas[] = {"SAMAMBAIA", "HIBISCO", "ABACATEIRO", "ABACAXI", "ABOBOREIRA", "ABSINTO",
			"ACÁCIA", "AÇAÍ", "AGRIÃO", "AGUAPÉ", "ALCACHOFRA", "ALFACE", "ALFAFA", "ALGODOEIRO", "ALHO", 
			"ALPISTE", "AMEIXEIRA", "AMENDOIM", "AMOREIRA", "ANGICO VERMELHO", "ANIS", "ARATICUM", "ARNICA",
			"ARROEIRA", "ARROZ", "ARRUDA", "ASPARGO", "AVEIA", "AVENCA", "BAMBU", "BANANEIRA", "BATATA",
			"BEGÔNIA", "BERGAMOTEIRA", "BERINJELA", "BETERRABA", "BOCA-DE-LEÃO", "BRACATINGA", "BRÓCOLIS",
			"CACAU", "CACTO", "CAFEEIRO", "CAJUEIRO", "CAMOMILA", "CANA-DE-AÇÚCAR", "CAQUIZEIRO", "CARNAÚBA", 
			"CASTANHEIRA-DO-PARÁ", "CEBOLA", "CANELA", "CENOURA", "CEREJEIRA", "CHICÓRIA", "CHORÃO", "CHUCHU",
			"CIDREIRA", "CIPRESTE", "CONFREI", "COQUEIRO", "COUVE-FLOR", "CRAVEIRO", "DÁLIA", "DAMASQUEIRO",
			"DENTE-DE-LEÃO", "ERVILHA", "ESPINAFRE", "EUCALIPTO", "FEIJOEIRO", "FIGUEIRA", "FRUTA-DE-CONDE",
			"FUNCHO", "GIRASSOL", "GLOXÍNIA", "GOIABEIRA", "GUARANÁ", "HERA", "HORTELÃ", "HORTÊNSIA",
			"INHAME", "IPÊ", "JABUTICABEIRA", "JACARANDÁ", "JAQUEIRA", "JOIO", "JUNCO", "LARANJEIRA",
			"LIMEIRA", "LIMOEIRO", "LIRIO", "LOUREIRO", "MAMOEIRO", "MAMONA", "MANDIOCA", "MANGUEIRA",
			"MANJERICÃO", "MANJERONA", "MARACUJAZEIRO", "MELANCIA", "MELÃO", "MILHO", "MOGNO", "MORANGUEIRO",
			"MOSTARDA", "NABO", "NECTARINA", "NOGUEIRA", "ORÉGANO", "PAINEIRA", "PALMITEIRO", "PAPOULA",
			"PARREIRA", "PATA-DE-VACA", "PEPINO", "PEREIRA", "PESSEGUEIRO", "PIMENTA MALAGUETA", "PIMENTA-DO-REINO",
			"PIMENTÃO", "PINHEIRO", "PINUS", "PITANGUEIRA", "POEJO", "PORONGO", "QUEBRA-PEDRA", "RABANETE",
			"REPOLHO", "ROMÃZEIRA", "ROSEIRA", "RÚCULA", "SALGUEIRO", "SALSA", "SALVIA", "SÂNDALO", "SOJA",
			"SORGO", "TABUA", "TAMAREIRA", "TANGERINA", "TOMATEIRO", "TREVO", "TRIGO", "TULIPA", "URTIGA",
			"UVAIA", "VASSOURA", "VIMEIRO", "VIOLETA", "XAXIM"};
	private String nomesEsportes[] = {"FUTEBOL", "XADREZ", "AIKIDO", "ATLETISMO", "AUTOMOBILISMO", "ARREMESSO DE PESO",
			"BADMINTON", "BASQUETE", "BASEBOL", "BOBSLED", "BOLICHE", "BOXE", "CANOAGEM", "CAPOEIRA", "CICLISMO",
			"CORRIDA LIVRE", "CROSS COUNTRY", "CROSSFIT", "CURLING", "DAMA", "ESCALADA", "ESQUI", "ESGRIMA", 
			"FUTEBOL AMERICANO", "FUTEBOL DE AREIA", "FUTSAL", "GINÁSTICA", "GOLFE", "HANDEBOL", "HIGHLINE",
			"HIPISMO", "HÓQUEI", "IAIDO", "JIU-JITSU", "JUDÔ", "KENJUTSU", "KART", "KARATÊ", "KICKBOXING",
			"KITESURFE", "KUNG FU", "LEVANTAMENTO DE PESO", "MARATONA", "MOTOCICLISMO", "MOUNTAIN BIKE",
			"MUAY THAI", "NATAÇÃO", "NINJUTSU", "QUEIMADA", "PARAPENTE", "PATINAÇÃO", "POLO AQUÁTICO", "REMO",
			"RUGBY", "SALTOS ORNAMENTAIS", "SKATE", "SLACKLINE", "SNOWBOARD", "STANDUP PADDLE", "SURFE",
			"TAEKWONDO", "TIRO COM ARCO", "TRIATLO", "TÊNIS", "TÊNIS DE MESA", "VELA", "VÔLEI", "WINDSURF"};
	private String timesFutebol[] = {"ARSENAL", "ASTON VILLA", "ATALANTA", "ATHLETIC BILBAO", "BAHIA", "BANGU",
			"BARCELONA", "BAYERN DE MUNIQUE", "BENFICA", "BETIS", "BOCA JUNIORS", "BOCA JÚNIOR", "BORUSSIA DORTMUND",
			"BOTAFOGO", "BOURNEMOUTH", "BRAGANTINO", "CABOFRIENSE", "CAGLIARI", "CEARÁ", "CHAPECOENSE", "CHELSEA",
			"CHIEVO", "CORINTHIANS", "CORITIBA", "CRUZEIRO", "CRYSTAL PALACE", "EVERTON", "FLAMENGO", "FLUMINENSE",
			"FORTALEZA", "GENOA", "GETAFE", "GIRONA", "GRANADA", "GRÊMIO", "HANNOVER", "HUDDERSFIELD", "INTERNAZIONALE",
			"KÖLN", "JUVENTUS", "LEICESTER", "LEVANTE", "LIVERPOOL", "LUZIÂNIA", "MALLORCA", "MANCHESTER CITY",
			"MANCHESTER UNITED", "MILAN", "NAPOLI", "NEWCASTLE", "NORWICH CITY", "PSV EINDHOVEN", "PALERMO", "PALMEIRAS",
			"PARIS SAINT-GERMAIN", "PARMA", "PONTE PRETA", "PORTO", "PORTUGUESA", "QUEENS PARK RANGERS", "RAYO VALLECANO",
			"REAL MADRID", "REAL SOCIEDAD", "RIVER PLATE", "ROMA", "SANTA CRUZ", "SANTOS", "SASSUOLO", "SCHALKE",
			"SEVILLA", "SHAKHTAR DONETSK", "SOUTHAMPTON", "SPARTA", "STOKE CITY", "SUNDERLAND", "SWANSEA CITY", 
			"SÃO PAULO", "TORINO", "TOTTENHAM", "UDINESE", "VALENCIA", "VALLADOLID", "VASCO", "VILLARREAL", "VITÓRIA",
			"WATFORD", "WERDER BREMEN", "WEST BROMWICH", "WEST HAM", "WIGAN", "WOLVERHAMPTON", "ZARAGOZA", "ZENIT"};
	
	public String[] getNomeFeminino() {
		return nomeFeminino;
	}
	public String[] getNomeMasculino() {
		return nomeMasculino;
	}
	public String[] getPaises() {
		return paises;
	}
	public String[] getCidades() {
		return cidades;
	}
	public String[] getAnimais() {
		return animais;
	}
	public String[] getPlantas() {
		return plantas;
	}
	public String[] getNomesEsportes() {
		return nomesEsportes;
	}
	public String[] getTimesFutebol() {
		return timesFutebol;
	}
	
}
